global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['siem_alertmanager:9093']

scrape_configs:
  - job_name: 'siem_mock_environment'
    static_configs:
      - targets: ['siem_generator:8001', 'siem_engine:8002']
