{
 "title": "SIEM Observability Overview",
 "tags": [
  "siem",
  "security"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Authentication Logs Generated (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(mock_logs_generated_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active Tracked IPs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "siem_active_tracked_ips", "legendFormat": "IPs Tracking" }
   ]
  },
  {
   "title": "SIEM Alerts Generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "siem_alerts_generated_total", "legendFormat": "Alerts Fired" }
   ]
  },
  {
   "title": "Mean Time To Detect (MTTD)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(siem_mttd_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Malformed Logs (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(siem_logs_malformed_total[1m])",
     "legendFormat": "Malformed Rate"
    }
   ]
  },
  {
   "title": "Alerts by Rule ID",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum(siem_alerts_generated_total) by (rule_id)",
     "legendFormat": "{{rule_id}}"
    }
   ]
  }
 ]
}